### ISSUE TITLE
CLI integration

### ISSUE THREAD

**Issue by GFragniere** [Killian-Viquerat/DAI_Practical_Work_1_Magic_Image_CLI#4]
Started working on CLI integration including commands for wanted features.

**Comment by GFragniere** [comment]
Cannot finish the integration just yet, I need to have methods from other branches to finish it correctly

**Comment by Killian-Viquerat** [comment]
Added effect as an interface for each feature

**Comment by Killian-Viquerat** [comment]
Need to rework the all read write bmp file from the process command

**Comment by Killian-Viquerat** [comment]
Using this branch as a rework for how functionnality are called now that they are implemented
